// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOIDMmWRPuH85Mn1oIjCkK3wCxDuC26Nk',
    appId: '1:497166291587:web:251de8c8ee337355a341b6',
    messagingSenderId: '497166291587',
    projectId: 'praxisassistent-d229c',
    authDomain: 'praxisassistent-d229c.firebaseapp.com',
    storageBucket: 'praxisassistent-d229c.firebasestorage.app',
    measurementId: 'G-BB3PW1T959',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYTyuAA7cvgm5VzflfsqaorG1fM86zYz0',
    appId: '1:497166291587:android:87e60fd60905339ca341b6',
    messagingSenderId: '497166291587',
    projectId: 'praxisassistent-d229c',
    storageBucket: 'praxisassistent-d229c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8u_33_P8KESwLYwdYRAwkOihlfBPt0tU',
    appId: '1:497166291587:ios:1120d03922d63636a341b6',
    messagingSenderId: '497166291587',
    projectId: 'praxisassistent-d229c',
    storageBucket: 'praxisassistent-d229c.firebasestorage.app',
    iosBundleId: 'com.praxisassistent.praxisassistent',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8u_33_P8KESwLYwdYRAwkOihlfBPt0tU',
    appId: '1:497166291587:ios:1120d03922d63636a341b6',
    messagingSenderId: '497166291587',
    projectId: 'praxisassistent-d229c',
    storageBucket: 'praxisassistent-d229c.firebasestorage.app',
    iosBundleId: 'com.praxisassistent.praxisassistent',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBOIDMmWRPuH85Mn1oIjCkK3wCxDuC26Nk',
    appId: '1:497166291587:web:e64a389024e2c69da341b6',
    messagingSenderId: '497166291587',
    projectId: 'praxisassistent-d229c',
    authDomain: 'praxisassistent-d229c.firebaseapp.com',
    storageBucket: 'praxisassistent-d229c.firebasestorage.app',
    measurementId: 'G-KJP1J2B8QE',
  );

}